server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_account
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
    druid:
      aop-patterns: com.atguigu.admin.*
      filters: stat,wall,slf4j

      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

    #type: com.zaxxer.hikari.HikariDataSource
  redis:
    database: 5
    host: 172.16.63.9
    port: 6379
    password: redis_gdufms
    client-type: jedis

#mybatis:
#  #  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true