version: "3"

services:
  nginx: #服务名称
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/nginx/logs:/var/log/nginx
      - /root/nginx/conf:/etc/nginx/conf.d
    privileged: true #解决nginx文件调用的权限问题
  hello-test: #自己的jar包
    image: hello-test:latest
    container_name: hello-test
    build: . # 表示以当前目录下的dockerfile构建容器
    ports:
      - 8888:8888