server:
  port: 8888
spring:
  application:
    name: mqtt-demo
mqtt:
  host: tcp://172.16.1.171:1883
  version: 3.1.1
  username: mocar_easy_01
  password: mocar_easy_01
  #connectAttemptsMax: 3
  #reconnectAttemptsMax: 2
  enable: true
  msgTopic:
    testTopic: test
    streamStart: streamStart
    streamStop: streamEnd

