server:
  port: 8888
spring:
  application:
    name: mqtt-demo
mqtt:
  host: tcp://112.74.104.62:1883
  version: 3.1.1
  userName: admin
  password: admin
  connectAttemptsMax: 3
  reconnectAttemptsMax: 2
  #?????mqtt??????????
  enable: true
  msgTopic:
    #mqtt????
    gduStreamStart: gdu/realVideo/streamStart
    gduStreamStop: gdu/realVideo/streamEnd

