person:
  userName: zhangsan
  boss: true
  birth: 2019/12/9
  age: 18
  #interests: [篮球,足球]
  interests:
    - 篮球
    - 足球
    - 乒乓球
  animal: [阿猫,阿狗]
  #score:
    #english: 80
    #math: 90
  score: {english: 80,math: 90}
  salarys:
    - 9999.98
    - 9999.99
  pet:
    name: 阿狗
    weight: 50.59
  allPets:
    sick:
      - {name: 阿狗,weight: 50.59}
      - name: 阿猫
        weight: 88.58
      - name: 阿虫
        weight: 17.77
    health: [{name: 阿花,weight: 150.59},{name: 阿叶,weight: 100.59}]
